### ISSUE TITLE
Need backscatter detector/handler for receive-only addresses

### ISSUE THREAD

**Issue by SpareSimian** [The-McGrail-Foundation/MIMEDefang#27]
Feature request: I'm getting a lot of backscatter to receive-only "role" addresses like webmaster, hostmaster, and noc, addresses I use to register at ARIN or my domain registrar. I get maybe 20-50 of these a day. I'd like to have some way of detecting and rejecting them at the MTA. For example, I could provide a list of such addresses and the filter would check for common NDR patterns and bounce those for these addresses. Or perhaps a fancier filter could spot that the NDR is for an obvious forgery.

[Originally sent to the mailing list, which seems to be bouncing right now.]

**Comment by grumpybozo** [comment]
Because proper NDRs always use the null SMTP envelope sender, you can detect them in your mimedefang-filter script's 'filter_recipient()' subroutine, the point at which you know both the envelope sender and all recipients. it is also generally useful to reject any message there with a null sender that has more than one recipient (which cannot legitimately occur.)  The man page for mimedefang-filter has a simplistic example of how to reject mail for a particular sender+recipient pair, which could be adapted to reject mail from the null sender to any address in a list (which you could hardcode in mimedefang-filter or read from a file or database.)

Or if you prefer (because this is likely to be a relatively stable and short list of addresses) you can probably do it in your MTA. In Postfix this could be done with a restriction class and in Sendmail I believe that FEATURE(check_compat) and suitable entries in the access DB could be made to work.

**Comment by SpareSimian** [comment]
I've started to code up a filter_recipient for this purpose. 

I looked at the sendmail feature. A gotcha is that the ruleset is check_compat but enabling it is done with FEATURE(compat_check). I decided to go with the mimedefang filter, instead, to allow me to log possible matches before I start blocking them.
